Repository mosdef-hub/foyer, pull requests merged in 2019-05, with the labels that each got.

#231 Use built-in sets for whitelists & blacklists
  devtools/conda-recipe/meta.yaml
  foyer/smarts_graph.py
  requirements-dev.txt
  requirements.txt
Labels: maintenance

#215 Add some issue/PR templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/QUESTION.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: maintenance

#214 Add a contributor's guide
  CONTRIBUTING.md
Labels: maintenance

#161 Generate a Foyer XML from a parameterized ParmEd Structure
  foyer/forcefield.py
  foyer/tests/files/oplsaa-periodic.xml
  foyer/tests/test_forcefield.py
  foyer/xml_writer.py
Labels: WIP

#165 Charmm torsions allowable in forcefield XML files
  foyer/forcefield.py
  foyer/forcefields/ff.xsd
  foyer/tests/files/charmm36_cooh.xml
  foyer/tests/test_forcefield.py
Labels: feature

#245 Add conftest.py to store pytest fixtures
  foyer/tests/conftest.py
Labels: testing
