Repository mosdef-hub/foyer, pull requests merged in 2019-06, with the labels that each got.

#251 Update links for COMMAT paper
  README.md
  docs/citing_foyer.rst
  docs/files/foyer_citation.bib
  docs/files/foyer_citation.ris
  docs/index.rst
Labels: documentation

#184 Feat/skip empty def
  foyer/atomtyper.py
  foyer/forcefield.py
  foyer/tests/files/empty_def.xml
  foyer/tests/test_forcefield.py
  foyer/validator.py
Labels: atomtyping, feature

#257 Drop Python 2.7 from travis and docs
  .travis.yml
  docs/installation.rst
Labels: maintenance
